version: '3.8'

services:
  feishu-admin-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: feishu-admin-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - 2026-e_ink_billboard_backend_eink-net
      - feishu-admin-network

networks:
  feishu-admin-network:
    driver: bridge
  2026-e_ink_billboard_backend_eink-net:
    external: true
